name: Continuous Integration
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "30 8 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: python:3.9.7-slim-bullseye
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install pipenv
        run: pip install pipenv
      - name: Update dependencies
        run: pipenv sync --dev
      - name: Type check
        run: ./tool/check-types.sh
      - name: Unit tests
        run: ./tool/check-tests.sh
      - name: Format check
        run: ./tool/check-format.sh
      - name: Lint check
        run: ./tool/check-lints.sh
