name: Scheduled Update
on:
  workflow_dispatch:
  schedule:
    - cron: "30 0,6,12,18 * * *"
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: glesica/mtdata:latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tool
        run: mtdata --out $GITHUB_WORKSPACE/data
      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: data
          author_name: Automated
          author_email: actions@users.noreply.github.com
          message: Update data
          pathspec_error_handling: exitImmediately
          pull_strategy: NO-PULL
